version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 16
        commands:
            - npm install
            - npm run build
artifacts:
    files:
        - '**/*'
    base-directory: out
